version: "3"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:latest
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
    command:
      # 执行的命令
      redis-server /usr/local/etc/redis/redis.conf 

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  # rabbit1:
  #   image: rabbitmq:management
  #   hostname: rabbit1
  #   ports:
  #     - 5672:5672 #集群内部访问的端口
  #     - 15672:15672
  #   environment: 
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER} 
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    
  # rabbit2:
  #   image: rabbitmq:management
  #   hostname: rabbit2
  #   ports:
  #     - 5673:5672 #集群内部访问的端口
  #     - 15673:15672
  #   environment:
  #     - CLUSTERED=true
  #     - CLUSTER_WITH=rabbit1
  #     - RAM_NODE=true
  #   links:
  #     - rabbit1

  # rabbit3:
  #   image: rabbitmq:management
  #   hostname: rabbit3
  #   ports:
  #     - 5674:5672 #集群内部访问的端口
  #   environment:
  #     - CLUSTERED=true
  #     - CLUSTER_WITH=rabbit1
  #   links:
  #     - rabbit1
  #     - rabbit2